# Generated by Django 5.0.6 on 2024-06-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_movimentacao_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacao",
            options={"ordering": ["ocorrencia", "pk"]},
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="ocorrencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentacoes",
                to="crm.ocorrencia",
            ),
        ),
    ]
