# Generated by Django 5.0.6 on 2024-06-14 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_movimentacao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 14, 8, 57, 11, 713902)
            ),
        ),
    ]
